baseURL = 'https://jayhuangsci.github.io/'
languageCode = 'en-us'
title = 'Jay Huang'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
      [markup.goldmark.extensions.cjk]
        enable = true
        escapedSpace = true
        eastAsianLineBreaks = true
        eastAsianLineBreaksStyle = 'simple'
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\[', '\]']]
          inline = [['$', '$'], ['\(', '\)']]

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true
    style = 'xcode'
